sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    Note right of browser: New note is sent as JSON data
    server-->>browser: 201 Created 
    deactivate server
    Note right of browser: Browser updates the page dynamically without reload
